### PR TITLE
No longer redraws all tracks on label edit/delete

### PR DESCRIPTION
**Pull request by deltarod**
Given the previous changes, all tracks no longer need to be redrawn for an edit/delete.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Nice work :)

**Comment by deltarod** [comment]
@cmdcolin I think this has a good amount of polish on it. Want to check it over and merge it? The only thing I want to add to it or the capstone team might add to it is a right click menu for label customization

**Comment by cmdcolin** [comment]
Sure, I'll go ahead and merge

**Comment by cmdcolin** [comment]
As far as right click, I guess depending on if you want native jbrowse menus or other native jbrowse stuff could require a little expert knowledge, but can also make your own little onclick action or popup

**Comment by deltarod** [comment]
I have tried a ton of different ways to try and catch the context menu and I cant, I think a jbrowse solution would be easier as it has it already handled and would make it easier to support in the future.

**Comment by cmdcolin** [comment]
@deltarod can you fix the instance in http://localhost/jbrowse/?data=plugins/InteractivePeakAnnotator/test/data possibly

It fails after highlight with "callback not a function"

**Comment by cmdcolin** [comment]
The instance at http://localhost/jbrowse/?data=plugins/InteractivePeakAnnotator/test/data  is my primary way of testing the code since I am not hooked up to any larger system using this

**Comment by deltarod** [comment]
Why are you using localhost/jbrowse/ ? All of my testing urls look like [http://localhost/?data=plugins/InteractivePeakAnnotator/test/data](http://localhost/?data=plugins/InteractivePeakAnnotator/test/data)

**Comment by cmdcolin** [comment]
I just deploy jbrowse in a subfolder called jbrowse, probably not of too much consequence. I just mean that, in order for me to test, I have to test this plugin with the test/data directory folder in this plugin, and from what I can tell, the test/data/ folder gives that callback error

**Comment by deltarod** [comment]
I'm silly and the URL is besides the point, I've refactored IPA to be more like WiggleHighlighter with a Base.js and feature mixins. The issue here was an XYPlot not behaving correctly because I hadn't changed the XYPlot file. I'm about to push a PR for this.

**Pull request merged**
