### PR TITLE
Refactor of label system

### PR DESCRIPTION
**Pull request by deltarod**
The current system is very set in stone, allowing for very little flexibility in the storage of these labels. This refactor changes how values are retrieved, allowing for modularity in the storage system. An example of a different storage system can be found [here](https://github.com/deltarod/PeakLearnerBackend).

### CODE REVIEW

**Comment by deltarod** [comment]
Fixed the test/data stuff, I just hadn't changed XYPlot to fit the changes made.

**Comment by cmdcolin** [comment]
do you think you can add the clearHighlight back? and also it creates things with label undefined by default, maybe hide label if undefined? not sure if that is this module or wigglehighlighter

localhost_jbrowse__data=plugins%2FInteractivePeakAnnotator%2Ftest%2Fdata loc=ctgA%3A7222 24795 tracks=interactive3%2Cinteractive%2Cinteractive2 highlight=

**Comment by deltarod** [comment]
The default line value is assigned here: https://github.com/deltarod/interactivepeakannotator/blob/4de2d3e6d5265cdad0766098fa8a514873be8a79/js/Store/SeqFeature/Features.js#L35

What do you mean about clearHighlight?

**Comment by cmdcolin** [comment]
The clearHighlight was removed in globalHighlightChanged listener in the new code. This was the old one https://github.com/cmdcolin/interactivepeakannotator/pull/4/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafL18

That makes the highlight go away instantly after selecting a region

**Comment by deltarod** [comment]
Okay, I moved the delete function to right click, instead of functioning when highlightFlag is set to 0. Because I am subscribing to event globalHighlightChanged, when the highlight is cleared it would revert to the delete functionality instead of the change label functionality.

**Comment by cmdcolin** [comment]
I think this is pretty good. The responsibility of the clearHighlight to be in the XYPlot as opposed to the MultiXYPlot is a bit arbitrary and maybe it could be back in the src/main as an extra globalHighlightChanged listener that just clears it, but hard to say. Maybe I'll merge for now and can iterate

**Comment by deltarod** [comment]
I was looking at refactoring it to work similar to WiggleHighlighter with a feature mixin but quickly gave up. That would probably be the best way for reusability sake but I quickly got confused. I'd also like to remove the right click context menu when deleting.

**Comment by cmdcolin** [comment]
I think the right click may want to be preventDefault'd, it pops up a browser context menu on my machine?

**Comment by deltarod** [comment]
Why is this not being handled by the stopPropogation call here?: https://github.com/cmdcolin/wigglehighlighter/blob/265e812f0275a6e57e31e4a7420f2a2279d80f6f/js/View/Track/Base.js#L104

**Comment by deltarod** [comment]
Bump on this @cmdcolin

**Comment by cmdcolin** [comment]
I think stopPropagation would not stop the right click menu that would be preventDefault, however even that doesn't really help. I will merge this for now, can iterate on it

**Comment by cmdcolin** [comment]
Thanks for reminding me about this :)

**Comment by deltarod** [comment]
`
          const contextCallback = event => {
              console.log("Test")
              event.preventDefault()
              this.getConf('onContextMenu', [feature, this])
          }
          on(indicator, 'contextmenu', contextCallback);
          on(ret, 'contextmenu', contextCallback);
          if(label)
          {
              on(label, 'contextmenu', contextCallback);
          }
`
If I do something like this, the contextCallback is never called. This is in Base.js for WiggleHighlighter

**Comment by deltarod** [comment]
If it can't be figured out, I think the best plan of action would be to create a menu of some sort on left click, allowing the user to select the label for the highlight or delete the highlight

**Comment by cmdcolin** [comment]
Ya no worries. I'll let you make the call on that!

**Pull request merged**
